---
- name: ensure iam role is created
  iam_role:
    # Fixed values
    state: present
    # Required values
    name: "{{ iam.name }}"
    assume_role_policy_document: "{{ iam.assume_role_policy_document }}"
    # Optional values
    region: "{{ iam.region | default(aws_iam_default_region | default(omit)) }}"
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit) }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_iam_profile | default(omit) }}"
    managed_policy: "{{ iam.managed_policy | default(omit) }}"
    path: "{{ iam.path | default(omit) }}"
    description: "{{ iam.description | default(omit) }}"
    purge_policies: "{{ iam.purge_policies | default(true) }}"
