---
- name: Make sure user does not specify both policy_name and policy_json
  assert:
    that:
      - iam.policy_json is defined or iam.policy_name is defined
      - not (iam.policy_json is defined and iam.policy_document is defined)
    msg: "One of policy_json _or_ policy_document must defined."
- name: ensure iam policy is created
  iam_policy:
    # Fixed values
    state: present
    # Required values
    iam_name: "{{ iam.iam_name }}"
    iam_type: "{{ iam.type }}"
    policy_name: "{{ iam.policy_name }}"
    policy_json: "{{ iam.policy_json | default(omit) }}"
    # Optional values
    region: "{{ iam.region | default(aws_iam_default_region | default(omit)) }}"
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit) }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_iam_profile | default(omit) }}"
    policy_document: "{{ iam.policy_document | default(omit) }}"
    skip_duplicates: "{{ iam.skip_duplicates | default(omit) }}"
